import { firebaseConfig } from './firebase-config.js';
import { initializeApp, getApps, deleteApp } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';
import {
  getAuth, signInWithEmailAndPassword, signOut, onAuthStateChanged,
  createUserWithEmailAndPassword
} from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js';
import {
  getFirestore, collection, doc, getDoc, getDocs, addDoc, setDoc, updateDoc,
  deleteDoc, onSnapshot, runTransaction, writeBatch, serverTimestamp,
  query, where
} from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js';

const $=s=>document.querySelector(s);
const main=$('#main'),topActions=$('#topActions');
const params=new URLSearchParams(location.search);
const crewSlug=String(params.get('crew')||'').trim().toLowerCase();
const FLEX='__FLEX__',FLEX_LABEL='No preference / fill a gap';
const DEFAULT_SINGLE_UFN='UFN Vanguard',DEFAULT_DUAL_UFN='UFN Celeste',DEFAULT_DUAL_GHOST='GST Darkwater';
const ROLES=[{name:'Captain',colour:'command'},{name:'Helm',colour:'helm'},{name:'Weapons',colour:'weapons'},{name:'Engineering',colour:'engineering'},{name:'Science',colour:'science'},{name:'Relay',colour:'relay'}];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normalize=s=>String(s||'').normalize('NFKC').trim().toLocaleLowerCase().replace(/\s+/g,' ');
const claimId=name=>encodeURIComponent(normalize(name));
const capFor=()=>6;
const roleClass=r=>`role-${String(r).replace(/[^A-Za-z]/g,'')}`;
const dateText=v=>{if(!v)return 'Date not set';const [y,m,d]=String(v).split('-').map(Number);return new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(Date.UTC(y,m-1,d)));};

const appName=`campaign-portal-${crewSlug||'unknown'}`;
const app=getApps().find(a=>a.name===appName)||initializeApp(firebaseConfig,appName);
const auth=getAuth(app),db=getFirestore(app);
let crew=null,currentUser=null,activeDeployment=null,players=[],unsubs=[];

function clearUnsubs(){unsubs.forEach(fn=>{try{fn()}catch{}});unsubs=[];}
function msg(el,text,type=''){if(!el)return;el.textContent=text||'';el.className=`message${type?` ${type}`:''}`;}
function crewUrl(){return `${location.origin}${location.pathname}?crew=${encodeURIComponent(crewSlug)}`;}
function playerUrl(id){return `${location.origin}${location.pathname}?m=${encodeURIComponent(id)}`;}
function shipDefs(d){return [{id:'ufn',faction:'UFN',name:d.ufnShipName||DEFAULT_SINGLE_UFN}];}
function roleOptions(selected=''){return `<option value="">Choose…</option><option value="${FLEX}"${selected===FLEX?' selected':''}>${FLEX_LABEL}</option>`+ROLES.map(r=>`<option value="${r.name}"${selected===r.name?' selected':''}>${r.name}</option>`).join('');}
function lockRoleOptions(selected=''){return `<option value="">No station lock</option>`+ROLES.map(r=>`<option value="${r.name}"${selected===r.name?' selected':''}>${r.name}</option>`).join('');}
function preferenceTags(prefs=[]){return prefs.map((p,i)=>p===FLEX?`<span class="pref-tag">${i+1}. ${FLEX_LABEL}</span>`:`<span class="pref-tag ${roleClass(p)}">${i+1}. ${esc(p)}</span>`).join('');}
function setupPreferenceAutofill(ids){const sels=ids.map(id=>document.getElementById(id));if(sels.some(x=>!x))return;function sync(){if(sels[0].value===FLEX){sels[1].value=FLEX;sels[2].value=FLEX;sels[1].disabled=true;sels[2].disabled=true;return;}sels[1].disabled=false;if(sels[1].value===FLEX){sels[2].value=FLEX;sels[2].disabled=true;return;}sels[2].disabled=false;}sels.forEach(s=>s.addEventListener('change',sync));sync();}
function quality(p,role){if((p.dislikes||[]).includes(role))return{kind:'avoid',label:"Really don't want",cost:100000};for(let i=0;i<3;i++){const pref=p.prefs?.[i];if(pref===FLEX)return{kind:'flex',label:'Happy to fill a gap',cost:5000};if(pref===role)return{kind:'rank',rank:i+1,label:`${i+1}${i===0?'st':i===1?'nd':'rd'} choice`,cost:[0,100,500][i]};}return{kind:'other',label:'Other available station',cost:8000};}
function overrideFor(d,id){return d?.overrides?.[id]||{};}
function assignmentCost(p,slot,d,index){const o=overrideFor(d,p.id);if(o.shipId&&o.shipId!==slot.shipId)return Infinity;if(o.role&&o.role!==slot.role)return Infinity;const q=quality(p,slot.role);let cost=q.cost;if(p.shipPref&&p.shipPref!==slot.shipId)cost+=20;cost+=index*0.00001;return cost;}
function addEdge(g,a,b,cap,cost){const f={to:b,rev:g[b].length,cap,cost};const r={to:a,rev:g[a].length,cap:0,cost:-cost};g[a].push(f);g[b].push(r);return f;}
function minCostFlow(g,s,t,want){let flow=0;while(flow<want){const n=g.length,dist=Array(n).fill(Infinity),pv=Array(n).fill(-1),pe=Array(n).fill(-1),inq=Array(n).fill(false),q=[s];dist[s]=0;inq[s]=true;while(q.length){const u=q.shift();inq[u]=false;for(let i=0;i<g[u].length;i++){const e=g[u][i];if(e.cap<=0)continue;const nd=dist[u]+e.cost;if(nd<dist[e.to]-1e-9){dist[e.to]=nd;pv[e.to]=u;pe[e.to]=i;if(!inq[e.to]){q.push(e.to);inq[e.to]=true;}}}}if(!Number.isFinite(dist[t]))break;let add=1;for(let v=t;v!==s;v=pv[v])if(pv[v]<0){add=0;break;}if(!add)break;for(let v=t;v!==s;v=pv[v]){const e=g[pv[v]][pe[v]];e.cap-=1;g[v][e.rev].cap+=1;}flow++;}return flow;}
function computePlan(list,d){const ships=shipDefs(d),slots=[];ships.forEach(ship=>ROLES.forEach(r=>slots.push({shipId:ship.id,ship,role:r.name,colour:r.colour})));const eligible=list.slice(0,capFor(d)),n=eligible.length,S=0,P=1,T=P+n,K=T+slots.length,g=Array.from({length:K+1},()=>[]),edges=Array.from({length:n},()=>[]);eligible.forEach((p,i)=>addEdge(g,S,P+i,1,0));slots.forEach((slot,j)=>addEdge(g,T+j,K,1,0));eligible.forEach((p,i)=>slots.forEach((slot,j)=>{const c=assignmentCost(p,slot,d,i);if(Number.isFinite(c))edges[i].push({edge:addEdge(g,P+i,T+j,1,c),j});}));if(minCostFlow(g,S,K,n)!==n)return{assignments:[],error:'The current organiser locks cannot all be satisfied.'};const assignments=[];eligible.forEach((p,i)=>{const used=edges[i].find(x=>x.edge.cap===0);if(!used)return;const slot=slots[used.j];assignments.push({playerId:p.id,name:p.name,shipId:slot.shipId,ship:slot.ship,role:slot.role,colour:slot.colour,quality:quality(p,slot.role),shipMet:!p.shipPref||p.shipPref===slot.shipId,forced:Boolean(overrideFor(d,p.id).shipId||overrideFor(d,p.id).role)});});return{assignments,error:''};}
function renderRoster(plan,d,admin=false){const ships=shipDefs(d);return `<div class="station-grid${ships.length===1?' one':''}">${ships.map(ship=>{const faction=ship.id==='ghosts'?'ghost':'',badge=ship.id==='ghosts'?'assets/ghost-faction.png':'assets/ufn-faction.png',strap=ship.id==='ghosts'?'ADAPT • INFILTRATE • DESTROY':'DISCIPLINE • HONOUR • VICTORY',map=new Map(plan.assignments.filter(a=>a.shipId===ship.id).map(a=>[a.role,a]));return `<section class="ship-card ${faction}"><div class="ship-brand"><img class="faction-badge" src="${badge}" alt="${esc(ship.faction)} insignia"><div class="ship-brand-copy"><div class="eyebrow">${ship.faction} crew</div><div class="ship-title">${esc(ship.name)}</div><div class="faction-strap">${strap}</div></div><span class="pill ${ship.id==='ghosts'?'ghost':'ufn'}">${[...map.values()].length}/6 crew</span></div>${ROLES.map(r=>{const a=map.get(r.name);return `<div class="station ${roleClass(r.name)}"><div class="station-role">${r.name}</div><div class="station-name">${a?esc(a.name):'<span class="sub">To be decided</span>'}</div>${admin&&a?`<div class="station-note">${esc(a.quality.label)}${a.shipMet?'':' · different ship preference'}${a.forced?' · organiser fixed':''}</div>`:''}</div>`}).join('')}</section>`;}).join('')}</div>${plan.error?`<div class="message error">${esc(plan.error)}</div>`:''}`;}
function validatePrefs(p){if(!p.name)return 'Enter a name.';if(!p.prefs?.[0]||!p.prefs?.[1]||!p.prefs?.[2])return `Choose all three station preferences, or use ${FLEX_LABEL}.`;const firstFlex=p.prefs.indexOf(FLEX);if(firstFlex>=0&&p.prefs.slice(firstFlex).some(x=>x!==FLEX))return `After ${FLEX_LABEL}, remaining choices should also be ${FLEX_LABEL}.`;const concrete=p.prefs.filter(x=>x!==FLEX);if(new Set(concrete).size!==concrete.length)return 'Choose different stations for ranked choices.';const clash=concrete.find(x=>(p.dislikes||[]).includes(x));if(clash)return `${clash} cannot be both preferred and really unwanted.`;return '';}

async function loadCrew(){
  if(!crewSlug){main.innerHTML='<section class="empty-state"><h2>Campaign link missing</h2><p>Ask the administrator for the campaign crew link.</p></section>';return;}
  try{
    const snap=await getDoc(doc(db,'ufnCampaignCrews',crewSlug));
    if(!snap.exists()){main.innerHTML='<section class="empty-state"><h2>Campaign crew not found</h2><p>Check the campaign link with the administrator.</p></section>';return;}
    crew={id:snap.id,...snap.data()};
    if(crew.active===false){main.innerHTML=`<section class="empty-state"><h2>${esc(crew.name)}</h2><p>This campaign crew system is currently disabled.</p></section>`;return;}
    onAuthStateChanged(auth,user=>{currentUser=user;if(user&&user.uid===crew.authUid){renderTop();renderDashboard();}else{if(user)signOut(auth).catch(()=>{});renderPasswordGate();}});
  }catch(e){main.innerHTML=`<section class="empty-state"><h2>Campaign unavailable</h2><p>${esc(e.message)}</p></section>`;}
}
function renderPasswordGate(){
  clearUnsubs();topActions.innerHTML='';
  main.innerHTML=`<section class="campaign-login-shell"><div class="panel campaign-login-card"><div class="eyebrow">Campaign crew planner</div><h1>${esc(crew.name)}</h1><p>Enter the shared campaign password to manage this crew's deployments.</p><form id="campaignLogin"><div class="field"><label>Campaign password</label><input id="campaignPassword" type="password" autocomplete="current-password" required autofocus></div><div class="actions"><button class="btn primary">Open campaign planner</button></div><div id="campaignLoginMessage" class="message"></div></form><div class="campaign-lock-note campaign-small">This password unlocks the campaign management area. Player deployment links do not require this password.</div></div></section>`;
  $('#campaignLogin').onsubmit=async e=>{e.preventDefault();try{msg($('#campaignLoginMessage'),'Checking password…');const result=await signInWithEmailAndPassword(auth,crew.authEmail,$('#campaignPassword').value);if(result.user.uid!==crew.authUid){await signOut(auth);throw new Error('Campaign credential is no longer valid.');}renderTop();renderDashboard();}catch(err){msg($('#campaignLoginMessage'),friendlyAuthError(err),'error');}};
}
function renderTop(){topActions.innerHTML=`<span class="pill ufn">${esc(crew.name)}</span><button id="crewSettings" class="btn ghost tiny">Campaign settings</button><button id="crewLock" class="btn ghost tiny">Lock planner</button>`;$('#crewSettings').onclick=openSettingsModal;$('#crewLock').onclick=async()=>{clearUnsubs();await signOut(auth);renderPasswordGate();};}
function friendlyAuthError(err){const code=err?.code||'';if(code.includes('invalid-credential')||code.includes('wrong-password')||code.includes('invalid-login-credentials'))return 'Incorrect campaign password.';if(code.includes('too-many-requests'))return 'Too many attempts. Firebase has temporarily limited sign-in attempts; try again later.';if(code.includes('operation-not-allowed'))return 'Campaign password sign-in is not enabled in Firebase yet.';return err?.message||String(err);}

async function renderDashboard(){
  clearUnsubs();activeDeployment=null;players=[];
  main.innerHTML=`<div class="page-head campaign-dashboard-head"><div><div class="eyebrow">Campaign crew planner</div><h1>${esc(crew.name)}</h1><p class="sub">Create deployments and share each player link with the campaign crew.</p></div><div class="campaign-dashboard-actions"><button id="copyCrewLink" class="btn ghost">Copy campaign link</button><button id="createDeployment" class="btn primary">Create deployment</button></div></div><div id="deployments" class="grid cards"><section class="loading-card"><div class="scanner"></div><p>Loading deployments…</p></section></div>`;
  $('#copyCrewLink').onclick=()=>navigator.clipboard.writeText(crewUrl());$('#createDeployment').onclick=()=>openDeploymentModal();
  const q=query(collection(db,'ufnDeployments'),where('campaignCrew','==',crewSlug));
  unsubs.push(onSnapshot(q,snap=>{const ds=snap.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));$('#deployments').innerHTML=ds.length?ds.map(renderDeploymentCard).join(''):`<section class="empty-state"><h2>No deployments yet</h2><p>Create this campaign's first deployment.</p></section>`;ds.forEach(d=>{document.querySelector(`[data-manage="${CSS.escape(d.id)}"]`)?.addEventListener('click',()=>manageDeployment(d.id));document.querySelector(`[data-copy="${CSS.escape(d.id)}"]`)?.addEventListener('click',()=>navigator.clipboard.writeText(playerUrl(d.id)));document.querySelector(`[data-delete-deployment="${CSS.escape(d.id)}"]`)?.addEventListener('click',()=>deleteDeployment(d));});},err=>{$('#deployments').innerHTML=`<section class="empty-state"><h2>Could not load deployments</h2><p>${esc(err.message)}</p></section>`;}));
}
function renderDeploymentCard(d){return `<section class="panel mission-card"><div class="mission-date">${esc(dateText(d.date))}</div><h2>${esc(d.title||'UFN Deployment')}</h2><p class="sub">${esc(d.ufnShipName||DEFAULT_SINGLE_UFN)}</p><div class="mission-meta"><span class="pill ${d.closed?'closed':'open'}">${d.closed?'Choices closed':'Choices open'}</span><span class="pill">${Number(d.responseCount||0)}/${capFor(d)} responses</span></div><div class="share-box"><input readonly value="${esc(playerUrl(d.id))}"><button class="btn ghost tiny" data-copy="${esc(d.id)}">Copy player link</button></div><div class="actions"><button class="btn primary" data-manage="${esc(d.id)}">Manage crew</button><button class="btn danger" data-delete-deployment="${esc(d.id)}">Delete</button></div></section>`;}
function openDeploymentModal(existing=null){
  const initialUfn=existing?.ufnShipName||DEFAULT_SINGLE_UFN;
  const wrap=document.createElement('div');wrap.className='modal-backdrop';
  wrap.innerHTML=`<section class="modal panel"><button class="btn ghost tiny modal-close">Close</button><div class="eyebrow">${esc(crew.name)}</div><h2>${existing?'Edit':'Create'} deployment</h2><form id="deploymentForm"><div class="field"><label>Deployment name</label><input id="depTitle" required maxlength="80" value="${esc(existing?.title||'')}"></div><div class="field"><label>Date</label><input id="depDate" type="date" required value="${esc(existing?.date||'')}"></div><div class="campaign-small campaign-warning"><b>Campaign deployments use one UFN ship only</b> · maximum 6 players.</div><div class="field" style="margin-top:12px"><label>UFN ship name</label><input id="ufnShip" maxlength="60" required value="${esc(initialUfn)}"></div><div class="actions"><button class="btn primary" type="submit">${existing?'Save setup':'Create deployment'}</button></div><div id="depMessage" class="message"></div></form></section>`;
  document.body.appendChild(wrap);wrap.querySelector('.modal-close').onclick=()=>wrap.remove();
  $('#deploymentForm').onsubmit=async e=>{e.preventDefault();const data={title:$('#depTitle').value.trim(),date:$('#depDate').value,shipCount:1,ufnShipName:$('#ufnShip').value.trim()||DEFAULT_SINGLE_UFN,ghostShipName:'',campaignCrew:crewSlug,closed:existing?.closed||false,overrides:existing?.overrides||{},responseCount:Number(existing?.responseCount||0),updatedAt:serverTimestamp(),createdAt:existing?.createdAt||serverTimestamp()};try{if(existing)await setDoc(doc(db,'ufnDeployments',existing.id),data,{merge:true});else await addDoc(collection(db,'ufnDeployments'),data);wrap.remove();}catch(err){msg($('#depMessage'),err.message,'error')}};
}

async function manageDeployment(id){
  clearUnsubs();const ref=doc(db,'ufnDeployments',id),snap=await getDoc(ref);if(!snap.exists()||snap.data().campaignCrew!==crewSlug){renderDashboard();return;}activeDeployment={id,...snap.data()};players=[];
  main.innerHTML=`<div class="deployment-visual-banner"><div class="deployment-visual-copy"><span>${esc(crew.name)} · Campaign deployment</span><b>${esc(activeDeployment.title)}</b><small>${esc(dateText(activeDeployment.date))}</small></div><div class="deployment-factions"><img src="assets/ufn-faction.png" alt="UFN"></div></div><div class="page-head compact-management-head"><div><button id="backDash" class="btn ghost tiny">← Campaign dashboard</button><div class="eyebrow" style="margin-top:10px">Crew management</div></div><div class="actions"><button id="downloadCrewPdf" class="btn primary">Download crew PDF</button><button id="setupBtn" class="btn ghost">Deployment setup</button><button id="toggleClosed" class="btn ${activeDeployment.closed?'success':'danger'}">${activeDeployment.closed?'Open choices':'Close choices'}</button><button id="deleteDeployment" class="btn danger">Delete deployment</button></div></div><div class="grid two"><aside><section class="panel"><h2>Player link</h2><p class="sub">Share this link with everyone who should add preferences.</p><div class="share-box"><input id="manageLink" readonly value="${esc(playerUrl(id))}"><button id="copyManageLink" class="btn primary tiny">Copy link</button></div><div id="responseStats" class="mission-meta"></div><div id="manageMessage" class="message"></div></section><section class="panel" style="margin-top:14px"><div class="panel-heading-actions"><h2>Responses</h2><button id="addPlayer" class="btn primary tiny">Add player</button></div><div class="field"><label>Registered player</label><select id="playerSelect" class="select-player"><option value="">Select a player…</option></select></div><div id="responseEditor" class="response-editor"><div class="sub">Select a registered player to view or edit their preferences and organiser locks.</div></div></section></aside><section class="panel"><div class="eyebrow">Live suggestion</div><h2>Current crew plan</h2><p class="sub">Station preferences are prioritised globally. Campaign ship/station locks are hard constraints.</p><div id="roster"></div></section></div>`;
  $('#backDash').onclick=()=>renderDashboard();$('#copyManageLink').onclick=()=>navigator.clipboard.writeText(playerUrl(id));$('#downloadCrewPdf').onclick=downloadCrewPdf;$('#addPlayer').onclick=()=>openPlayerModal(null);$('#setupBtn').onclick=()=>openDeploymentModal(activeDeployment);$('#toggleClosed').onclick=async()=>updateDoc(ref,{closed:!activeDeployment.closed,updatedAt:serverTimestamp()});$('#deleteDeployment').onclick=()=>deleteDeployment(activeDeployment);$('#playerSelect').onchange=()=>renderResponseEditor($('#playerSelect').value);
  unsubs.push(onSnapshot(ref,s=>{if(!s.exists())return renderDashboard();activeDeployment={id,...s.data()};if(activeDeployment.campaignCrew!==crewSlug)return renderDashboard();$('#toggleClosed').textContent=activeDeployment.closed?'Open choices':'Close choices';$('#toggleClosed').className=`btn ${activeDeployment.closed?'success':'danger'}`;refreshManage();}));
  unsubs.push(onSnapshot(collection(db,'ufnDeployments',id,'players'),snap2=>{players=snap2.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>String(a.name).localeCompare(String(b.name)));refreshManage();}));
}
function refreshManage(){if(!activeDeployment||!$('#roster'))return;const plan=computePlan(players,activeDeployment);$('#roster').innerHTML=renderRoster(plan,activeDeployment,true);$('#responseStats').innerHTML=`<span class="pill">${players.length}/${capFor(activeDeployment)} responses</span><span class="pill">${plan.assignments.filter(a=>a.quality.rank===1).length} first choices</span>`;const add=$('#addPlayer');if(add)add.disabled=players.length>=capFor(activeDeployment);const sel=$('#playerSelect'),keep=sel.value;sel.innerHTML='<option value="">Select a player…</option>'+players.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');if(players.some(p=>p.id===keep)){sel.value=keep;renderResponseEditor(keep);}else renderResponseEditor('');}
function renderResponseEditor(id){const box=$('#responseEditor');if(!box)return;const p=players.find(x=>x.id===id);if(!p){box.innerHTML='<div class="sub">Select a registered player to view or edit their preferences and organiser locks.</div>';return;}const plan=computePlan(players,activeDeployment),a=plan.assignments.find(x=>x.playerId===p.id),o=overrideFor(activeDeployment,p.id);box.innerHTML=`<h3>${esc(p.name)}</h3><div class="assignment">${a?`${esc(a.ship.name)} • ${esc(a.role)}`:'Awaiting assignment'}</div><div class="response-editor-grid"><div><div class="label">Station preferences</div><div class="prefs-preview">${preferenceTags(p.prefs||[])}</div><dl><dt>Really don't want</dt><dd>${(p.dislikes||[]).length?(p.dislikes||[]).map(esc).join(', '):'None'}</dd></dl></div><div><dl><dt>Current result</dt><dd>${a?esc(a.quality.label):'Awaiting assignment'}</dd><dt>Campaign ship</dt><dd>${esc(activeDeployment.ufnShipName)}</dd><dt>Campaign station lock</dt><dd>${o.role||'None'}</dd></dl><div class="actions"><button id="editPlayer" class="btn primary">Edit player</button><button id="deletePlayer" class="btn danger">Delete</button></div></div></div>`;$('#editPlayer').onclick=()=>openPlayerModal(p);$('#deletePlayer').onclick=()=>deletePlayer(p);}
function openPlayerModal(p=null){
  const isNew=!p;if(isNew&&players.length>=capFor(activeDeployment)){alert(`This deployment is full (${capFor(activeDeployment)} crew).`);return;}
  const playerRef=isNew?doc(collection(db,'ufnDeployments',activeDeployment.id,'players')):doc(db,'ufnDeployments',activeDeployment.id,'players',p.id),playerId=playerRef.id,o=isNew?{}:overrideFor(activeDeployment,p.id),initialPrefs=isNew?[FLEX,FLEX,FLEX]:(p.prefs||['','','']),initialDislikes=isNew?[]:(p.dislikes||[]);
  const wrap=document.createElement('div');wrap.className='modal-backdrop';wrap.innerHTML=`<section class="modal panel"><button class="btn ghost tiny modal-close">Close</button><div class="eyebrow">${isNew?'Campaign entry':'Player preferences'}</div><h2>${isNew?'Add player':esc(p.name)}</h2><form id="adminPlayerForm"><div class="field"><label>Player name</label><input id="apName" value="${esc(p?.name||'')}" required maxlength="60" autocomplete="off"></div><div class="field"><label>1st station</label><select id="ap1">${roleOptions(initialPrefs[0])}</select></div><div class="field"><label>2nd station</label><select id="ap2">${roleOptions(initialPrefs[1])}</select></div><div class="field"><label>3rd station</label><select id="ap3">${roleOptions(initialPrefs[2])}</select></div><div class="label">Really don't want</div><div id="apDislikes" class="checks">${ROLES.map(r=>`<label class="check"><input type="checkbox" value="${r.name}"${initialDislikes.includes(r.name)?' checked':''}><span>${r.name}</span></label>`).join('')}</div><h3 style="margin-top:14px">Campaign lock</h3><div class="field"><label>Lock to station</label><select id="lockRole">${lockRoleOptions(o.role||'')}</select></div><div class="actions"><button class="btn primary">${isNew?'Add player':'Save changes'}</button></div><div id="apMessage" class="message"></div></form></section>`;
  document.body.appendChild(wrap);wrap.querySelector('.modal-close').onclick=()=>wrap.remove();setupPreferenceAutofill(['ap1','ap2','ap3']);
  $('#adminPlayerForm').onsubmit=async e=>{e.preventDefault();const payload={name:$('#apName').value.trim(),shipPref:'',prefs:[$('#ap1').value,$('#ap2').value,$('#ap3').value],dislikes:[...$('#apDislikes').querySelectorAll('input:checked')].map(x=>x.value),source:isNew?'organiser':(p.source||'player'),updatedAt:serverTimestamp()},err=validatePrefs(payload);if(err)return msg($('#apMessage'),err,'error');const depRef=doc(db,'ufnDeployments',activeDeployment.id),shipId='',role=$('#lockRole').value,newClaimRef=doc(db,'ufnDeployments',activeDeployment.id,'nameClaims',claimId(payload.name));try{if(isNew){await runTransaction(db,async tx=>{const [depSnap,claimSnap]=await Promise.all([tx.get(depRef),tx.get(newClaimRef)]);if(!depSnap.exists())throw new Error('Deployment no longer exists.');const depData=depSnap.data();if(depData.campaignCrew!==crewSlug)throw new Error('This deployment belongs to another campaign.');if(Number(depData.responseCount||0)>=capFor(depData))throw new Error(`This deployment is full (${capFor(depData)} crew).`);if(claimSnap.exists())throw new Error('That name is already registered for this deployment.');const overrides={...(depData.overrides||{})};if(shipId||role)overrides[playerId]={shipId,role};tx.set(playerRef,{...payload,createdAt:serverTimestamp()});tx.set(newClaimRef,{playerId:currentUser.uid,playerDocId:playerId,name:payload.name,source:'organiser',updatedAt:serverTimestamp()});tx.update(depRef,{responseCount:Number(depData.responseCount||0)+1,overrides,updatedAt:serverTimestamp()});});}else if(p.source==='organiser'&&normalize(payload.name)!==normalize(p.name)){const oldClaimRef=doc(db,'ufnDeployments',activeDeployment.id,'nameClaims',claimId(p.name));await runTransaction(db,async tx=>{const [depSnap,newClaimSnap]=await Promise.all([tx.get(depRef),tx.get(newClaimRef)]);if(!depSnap.exists())throw new Error('Deployment no longer exists.');if(newClaimSnap.exists()&&newClaimSnap.data().playerDocId!==playerId)throw new Error('That name is already registered for this deployment.');const overrides={...(depSnap.data().overrides||{})};if(shipId||role)overrides[playerId]={shipId,role};else delete overrides[playerId];tx.update(playerRef,payload);tx.delete(oldClaimRef);tx.set(newClaimRef,{playerId:currentUser.uid,playerDocId:playerId,name:payload.name,source:'organiser',updatedAt:serverTimestamp()},{merge:true});tx.update(depRef,{overrides,updatedAt:serverTimestamp()});});}else{await updateDoc(playerRef,payload);const overrides={...(activeDeployment.overrides||{})};if(shipId||role)overrides[playerId]={shipId,role};else delete overrides[playerId];await updateDoc(depRef,{overrides,updatedAt:serverTimestamp()});}wrap.remove();}catch(ex){msg($('#apMessage'),ex.message,'error');}};
}
async function deletePlayer(p){if(!confirm(`Delete ${p.name} from this deployment?`))return;const depRef=doc(db,'ufnDeployments',activeDeployment.id),pRef=doc(db,'ufnDeployments',activeDeployment.id,'players',p.id),claimRef=doc(db,'ufnDeployments',activeDeployment.id,'nameClaims',claimId(p.name));await runTransaction(db,async tx=>{const dep=await tx.get(depRef);tx.delete(pRef);tx.delete(claimRef);if(dep.exists())tx.update(depRef,{responseCount:Math.max(0,Number(dep.data().responseCount||0)-1),updatedAt:serverTimestamp()});});}
async function deleteDeployment(d){const title=d?.title||'this deployment';if(!confirm(`Delete ${title}? This permanently removes the deployment and all registered players.`))return;if(prompt(`Type DELETE to permanently remove ${title}.`)!=='DELETE')return;try{const playerSnap=await getDocs(collection(db,'ufnDeployments',d.id,'players')),claimSnap=await getDocs(collection(db,'ufnDeployments',d.id,'nameClaims')),batch=writeBatch(db);playerSnap.docs.forEach(s=>batch.delete(s.ref));claimSnap.docs.forEach(s=>batch.delete(s.ref));batch.delete(doc(db,'ufnDeployments',d.id));await batch.commit();if(activeDeployment?.id===d.id)renderDashboard();}catch(err){alert(`Could not delete deployment: ${err.message}`);}}

function downloadCrewPdf(){
  if(!activeDeployment||!window.jspdf?.jsPDF)return msg($('#manageMessage'),'PDF generator is unavailable. Refresh and try again.','error');
  const plan=computePlan(players,activeDeployment);if(plan.error)return msg($('#manageMessage'),plan.error,'error');
  const {jsPDF}=window.jspdf,pdf=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'}),ships=shipDefs(activeDeployment);
  pdf.setFont('helvetica','bold');pdf.setFontSize(20);pdf.text(activeDeployment.title||'UFN Deployment',12,14);pdf.setFontSize(10);pdf.setFont('helvetica','normal');pdf.text(`${dateText(activeDeployment.date)}  •  ${crew.name}`,12,21);pdf.text(`${players.length}/${capFor(activeDeployment)} registered`,285,21,{align:'right'});
  const cardW=ships.length===1?273:132,gap=9,startX=12,startY=30;
  ships.forEach((ship,i)=>{const x=startX+i*(cardW+gap),map=new Map(plan.assignments.filter(a=>a.shipId===ship.id).map(a=>[a.role,a]));pdf.setDrawColor(120);pdf.roundedRect(x,startY,cardW,150,2,2);pdf.setFont('helvetica','bold');pdf.setFontSize(14);pdf.text(ship.name,x+6,startY+10);pdf.setFontSize(9);pdf.setFont('helvetica','normal');pdf.text(`${ship.faction} crew`,x+6,startY+16);ROLES.forEach((r,idx)=>{const y=startY+28+idx*19,a=map.get(r.name);pdf.setDrawColor(210);pdf.line(x+6,y+5,x+cardW-6,y+5);pdf.setFont('helvetica','bold');pdf.text(r.name,x+6,y);pdf.setFont('helvetica','normal');pdf.text(a?.name||'To be decided',x+cardW-6,y,{align:'right'});});});
  const safe=String(activeDeployment.title||'UFN-Deployment').replace(/[^a-z0-9-_ ]/gi,'').trim().replace(/\s+/g,'-')||'UFN-Deployment';pdf.save(`${safe}_Crew-Manifest.pdf`);msg($('#manageMessage'),'Crew PDF downloaded.','ok');
}

function openSettingsModal(){
  const wrap=document.createElement('div');wrap.className='modal-backdrop';
  wrap.innerHTML=`<section class="modal panel"><button class="btn ghost tiny modal-close">Close</button><div class="eyebrow">Campaign settings</div><h2>${esc(crew.name)}</h2><div class="field"><label>Campaign link</label><div class="share-box"><input readonly value="${esc(crewUrl())}"><button id="copyCampaignLink" type="button" class="btn ghost tiny">Copy</button></div></div><div class="campaign-divider"></div><h3>Change shared password</h3><p class="sub">Changing the password rotates this campaign's Firebase credential. Every existing campaign session loses database access and must sign in again.</p><form id="passwordForm"><div class="field"><label>New password</label><div class="campaign-password-row"><input id="newPassword" type="password" minlength="6" autocomplete="new-password" required><button id="showNewPassword" type="button" class="btn ghost tiny">Show</button></div><div class="campaign-small">Use 12+ characters for a shared campaign password.</div></div><div class="actions"><button class="btn danger">Change password</button></div><div id="passwordMessage" class="message"></div></form></section>`;
  document.body.appendChild(wrap);wrap.querySelector('.modal-close').onclick=()=>wrap.remove();$('#copyCampaignLink').onclick=()=>navigator.clipboard.writeText(crewUrl());$('#showNewPassword').onclick=()=>{const i=$('#newPassword'),show=i.type==='text';i.type=show?'password':'text';$('#showNewPassword').textContent=show?'Show':'Hide';};
  $('#passwordForm').onsubmit=async e=>{e.preventDefault();const password=$('#newPassword').value;if(password.length<6)return msg($('#passwordMessage'),'Use at least 6 characters; 12+ is recommended.','error');let bundle=null;try{msg($('#passwordMessage'),'Rotating campaign access…');bundle=await createNewCredential(password);await updateDoc(doc(db,'ufnCampaignCrews',crewSlug),{authUid:bundle.user.uid,authEmail:bundle.email,passwordVersion:Number(crew.passwordVersion||1)+1,passwordChangedAt:serverTimestamp(),updatedAt:serverTimestamp()});await signOut(bundle.tempAuth).catch(()=>{});await deleteApp(bundle.tempApp).catch(()=>{});await signOut(auth);wrap.remove();location.href=crewUrl();}catch(err){if(bundle){await signOut(bundle.tempAuth).catch(()=>{});await deleteApp(bundle.tempApp).catch(()=>{});}msg($('#passwordMessage'),friendlyAuthError(err),'error');}};
}
async function createNewCredential(password){const name=`campaign-rotate-${Date.now()}-${Math.random().toString(36).slice(2)}`,tempApp=initializeApp(firebaseConfig,name),tempAuth=getAuth(tempApp),id=(crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`).replace(/[^a-zA-Z0-9-]/g,''),email=`campaign-${id}@accounts.ufn.invalid`;try{const cred=await createUserWithEmailAndPassword(tempAuth,email,password);return{tempApp,tempAuth,user:cred.user,email};}catch(e){await deleteApp(tempApp).catch(()=>{});throw e;}}

loadCrew();
